name = "ai-gateway"
compatibility_date = "2024-12-05"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
account_id = "7e298a91c3274f38a33f93ebe112cd91"

[vars]
ENVIRONMENT = 'dev'
CUSTOM_HEADERS_TO_IGNORE = []

#
#Configuration for DEVELOPMENT environment
#
[env.staging]
name = "ai-gateway-dev"

[env.staging.vars]
ENVIRONMENT = 'staging'
CUSTOM_HEADERS_TO_IGNORE = []


#
#Configuration for PRODUCTION environment
#
[env.production]
name = "ai-gateway"
logpush=true

[env.production.vars]
ENVIRONMENT = 'production'
CUSTOM_HEADERS_TO_IGNORE = []
